import { motion } from 'framer-motion';
import { useState } from 'react';
import aboutHeroIllustration from '../assets/about-hero-illustration.webp';
import mitenMehta from '../assets/miten-mehta.webp';
import ranjitDongre from '../assets/ranjit-dongre-about.webp';
import vSrinath from '../assets/v-srinath.webp';
import navinJR from '../assets/navin-jr.webp';
import pSrinath from '../assets/p-srinath-about.webp';
import rohitPai from '../assets/rohit-pai.webp';

const AboutPage = () => {
  const [expandedFounder, setExpandedFounder] = useState(null);
  const [expandedLeader, setExpandedLeader] = useState(null);

  const scrollToContact = () => {
    document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' });
  };

  const founders = [
    {
      name: 'Miten Mehta',
      role: 'Fund Manager',
      image: mitenMehta,
      description: `Miten is the alchemist to Bellwether Capital. As Bellwether's CIO, his strategy is a blend of spotting superior businesses, uncompromising financial discipline, and turning on a dime if volatile markets demand so.

Miten's philosophy is acutely aligned to a promoter's outlook of his business. His bold and brave approach has led to many disproportionate outcomes. Although Bellwether has a multi-cap approach, alpha has typically been generated by businesses spotted very early in their evolution. We have seen our winners slowly migrate from the small-caps to the mid-caps and more recently our mid-caps touching the large-cap horizon.

Miten's investment style is capable of the scalability of a large investment house, without compromising on its boutique heritage. The chase for governance in picking investments allows us to run many miles while we sleep serene.

Miten's investment edge is where energy meets flexibility. A weekly routine of squash, the gym and the unpredictability of a golf ball ensures this edge remains sharp and nimble. As does the body, so shall the mind!`
    },
    {
      name: 'Ranjit Dongre',
      role: 'Client Relationships',
      image: ranjitDongre,
      description: `Ranjit leads Bellwether Capital's business strategy with a blend of financial acumen and a client centric approach.

Ranjit's approach to managing money is defined by asset allocation customised to a client's investment objectives and risk profile. This approach is not limited to the maths of money management and extends to behavioural coaching, emotion management and decision-making guidance.

Ranjit's construct places the client at the centre of the circle fenced by a strong personal connect and hand holding through financial turbulence, all with an eye on "your tomorrow".

Ranjit's passion is centred around attempting to hit a golf ball. As the ticker tape definitely has a mind of his own, so does a golf ball. Conviction is ALL.`
    }
  ];

  const leaders = [
    {
      name: 'V. Srinath',
      role: 'Head of Research',
      image: vSrinath,
      description: `With 18 years of experience and as Bellwether's Head of Research, V. Srinath brings a diverse understanding and a unique perspective across businesses, which allows ideas to illuminate and come out of the shadows. Srinath has an ability to sift through data, look beyond financial models and tap into opportunity.`,
      color: 'bg-green-100 border-green-500'
    },
    {
      name: 'Navin JR',
      role: 'Sr. Research Analyst',
      image: navinJR,
      description: `Navin JR applies a structured and process-oriented approach to picking businesses at their nascent stage. His sector-agnostic and value-oriented strategy results in unusual ideas rising to the surface. An ability to nurture these ideas has enabled Bellwether Capital to embrace uncertainty in the small cap space and generate alpha.`,
      color: 'bg-blue-100 border-blue-500'
    },
    {
      name: 'P. Srinath',
      role: 'Head of Operations',
      image: pSrinath,
      description: `With over 30 years of experience, P. Srinath assisted the two founders in setting up Bellwether Capital. As the Head of Operations, he oversees market operations, strategy, and client service.`,
      color: 'bg-orange-100 border-orange-500'
    },
    {
      name: 'Rohit Pai',
      role: 'Dealer',
      image: rohitPai,
      description: `Rohit is the dealing arm of Bellwether Capital. With over 20 years of experience, Rohit executes trades with a keen eye on volume and price and is in tune with the ticker tape.`,
      color: 'bg-purple-100 border-purple-500'
    }
  ];

  return (
    <div className="pt-20">
      {/* Hero Section */}
      <section className="section-navy section-padding overflow-hidden">
        <div className="container-custom">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
            >
              <h1 className="heading-xl mb-6 text-white">
                At Bellwether, we manage money to help transform lives
              </h1>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="relative"
            >
              <img src={aboutHeroIllustration} alt="Bellwether Capital" className="w-full h-auto" />
            </motion.div>
          </div>
        </div>
      </section>

      {/* Introduction Section */}
      <section className="section-beige section-padding">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="max-w-4xl"
          >
            <h2 className="heading-md mb-8 text-navy">
              We are a boutique investment house committed to crafting our clients' financial freedom
            </h2>
            <p className="text-xl mb-6 text-navy/80">
              The arithmetic of our portfolio management strives to meet the emotional quotient of our clients and emphasises on delayed gratification to lead to asymmetric outcomes.
            </p>
            <p className="text-xl mb-8 text-navy/80">
              With two decades in the financial markets, we are ideally positioned to leverage our experience to empower our clients to build a legacy that goes beyond wealth.
            </p>
            <button onClick={scrollToContact} className="btn-primary">
              Get In Touch
            </button>
          </motion.div>
        </div>
      </section>

      {/* Founding Team Section */}
      <section className="section-beige section-padding">
        <div className="container-custom">
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="heading-lg mb-16 text-navy"
          >
            Bellwether's Founding Team
          </motion.h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
            {founders.map((founder, index) => (
              <motion.div
                key={founder.name}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="group"
              >
                <div className="bg-white rounded-3xl overflow-hidden shadow-lg hover-lift">
                  <img src={founder.image} alt={founder.name} className="w-full h-96 object-cover" />
                  <div className="p-6">
                    <button
                      onClick={() => setExpandedFounder(expandedFounder === index ? null : index)}
                      className="w-full text-left"
                    >
                      <h3 className="text-2xl font-semibold text-navy mb-2 flex items-center justify-between">
                        {founder.name}
                        <span className="text-sm text-green">
                          {expandedFounder === index ? '−' : '+'}
                        </span>
                      </h3>
                      <p className="text-navy/60">{founder.role}</p>
                    </button>
                    
                    <motion.div
                      initial={false}
                      animate={{
                        height: expandedFounder === index ? 'auto' : 0,
                        opacity: expandedFounder === index ? 1 : 0
                      }}
                      transition={{ duration: 0.3 }}
                      className="overflow-hidden"
                    >
                      <div className="pt-4 text-navy/70 whitespace-pre-line">
                        {founder.description}
                      </div>
                    </motion.div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Team Leading Section */}
      <section className="section-beige section-padding">
        <div className="container-custom">
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="heading-lg mb-16 text-navy"
          >
            Team Leading Bellwether
          </motion.h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {leaders.map((leader, index) => (
              <motion.div
                key={leader.name}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="group"
              >
                <div className="bg-white rounded-3xl overflow-hidden shadow-lg hover-lift">
                  <img src={leader.image} alt={leader.name} className="w-full h-80 object-cover" />
                  <div className="p-6">
                    <button
                      onClick={() => setExpandedLeader(expandedLeader === index ? null : index)}
                      className={`w-full text-left p-4 rounded-xl border-2 transition-all ${
                        expandedLeader === index ? leader.color : 'bg-gray-50 border-gray-200'
                      }`}
                    >
                      <h3 className="text-xl font-semibold text-navy mb-2 flex items-center justify-between">
                        {leader.name}
                        <span className="text-sm">
                          {expandedLeader === index ? '−' : '+'}
                        </span>
                      </h3>
                      <p className="text-navy/60 text-sm">{leader.role}</p>
                    </button>
                    
                    <motion.div
                      initial={false}
                      animate={{
                        height: expandedLeader === index ? 'auto' : 0,
                        opacity: expandedLeader === index ? 1 : 0
                      }}
                      transition={{ duration: 0.3 }}
                      className="overflow-hidden"
                    >
                      <div className="pt-4 text-navy/70 text-sm">
                        {leader.description}
                      </div>
                    </motion.div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* The Whole Team Section */}
      <section className="section-beige section-padding">
        <div className="container-custom">
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="heading-lg mb-16 text-navy"
          >
            The Whole Team
          </motion.h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {[
              { name: 'Kumar M', role: 'Research Analyst', experience: '9 years of experience' },
              { name: 'Aman Srivastav', role: 'Research Analyst', experience: '10 years of experience' },
              { name: 'Surbhi Soni', role: 'Research Analyst', experience: '4 years of experience' },
              { name: 'Mangesh Kolekar', role: 'Head of Compliance', experience: '20 years of experience' },
              { name: 'Kushal Dere', role: 'Head of Accounts', experience: '20 years of experience' },
              { name: 'Jyoti Mirchandani', role: 'Executive Assistant', experience: '15 years of experience' },
            ].map((member, index) => (
              <motion.div
                key={member.name}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="bg-white rounded-3xl p-6 shadow-lg hover-lift"
              >
                <h3 className="text-xl font-semibold text-navy mb-2">{member.name}</h3>
                <p className="text-navy/60 mb-1">{member.role}</p>
                <p className="text-sm text-navy/50">{member.experience}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact Information Section */}
      <section className="section-beige section-padding">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="max-w-2xl"
          >
            <h2 className="heading-md mb-8 text-navy">Reach Us</h2>
            <div className="space-y-6">
              <div>
                <p className="text-xl text-navy">
                  405, Raheja Chambers, Free Press Journal Road, Nariman Point, Mumbai 400 021
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-navy mb-2">Hours</h3>
                <p className="text-navy/70">Monday–Friday</p>
                <p className="text-navy/70">9am–6pm</p>
              </div>
              <div>
                <h3 className="font-semibold text-navy mb-2">Phone</h3>
                <a href="tel:+912266548178" className="text-navy hover:text-green transition-colors">
                  +91 22 6654 8178
                </a>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default AboutPage;
